{% set name = "pylance" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lancedb/lance/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 07ef724dff55b1125291f0bfbd0e2f08e453f508fe6ca98d1ad9d34b11dc70ad

build:
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - libprotobuf
  host:
    - python
    - pip
    - maturin <2
    - openssl
  run:
    - python
    - numpy >=1.22
    - pyarrow >=14
    - lance-namespace >=0.5.2
{% set tests_to_skip = "test_all_permutations" %}
{% set tests_to_skip = tests_to_skip + " or test_backward_compatibility_changed_index_protos" %}
{% set tests_to_skip = tests_to_skip + " or test_fts_backward_v0_27_0" %}

{% set tests_to_skip = tests_to_skip + " or test_torch_index_with_nans" %}
{% set tests_to_skip = tests_to_skip + " or test_index_with_no_centroid_movement" %}
{% set tests_to_skip = tests_to_skip + " or test_index_cast_centroids" %}

{% set tests_to_skip = tests_to_skip + " or test_create_index_unsupported_accelerator" %} # [py==314]

{% set tests_to_skip = tests_to_skip + " or test_ground_truth" %}
{% set tests_to_skip = tests_to_skip + " or test_cosine_distance" %}
{% set tests_to_skip = tests_to_skip + " or test_pairwise_cosine" %}
{% set tests_to_skip = tests_to_skip + " or test_l2_distance" %}
{% set tests_to_skip = tests_to_skip + " or test_l2_distance_f16_bf16_cpu" %}
{% set tests_to_skip = tests_to_skip + " or test_torch_kmeans_nans" %}

{% set test_files_to_skip = "--ignore python/tests/test_table_provider.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore python/tests/test_migration.py" %}
# pytorch not available for testing on python 3.14
{% set test_files_to_skip = test_files_to_skip + " --ignore python/tests/torch_tests" %}  # [py==314]

{% set markers_to_skip = "cuda or slow or gpu" %}
# pytorch not available for testing on python 3.14
{% set markers_to_skip = markers_to_skip + " or torch" %} # [py==314]

test:
  source_files:
    - python/pyproject.toml
    - python/python/tests
  imports:
    - lance
  commands:
    - pip check
    - cd python
    
    - pytest -v -s -m "not ({{ markers_to_skip }})" -k "not ({{ tests_to_skip }})" {{ test_files_to_skip }} python/tests 

  requires:
    - pip
    - pytest
    - tqdm
    - pandas
    - pillow
    - duckdb
    - datasets
    - polars
    - ml_dtypes
    - psutil
    - pytorch
    - pytest-timeout

about:
  home: https://lance.org/
  summary: python wrapper for Lance columnar format
  description: |
    Lance is an open lakehouse format for multimodal AI. It contains a file
    format, table format, and catalog spec that allows you to build a complete
    lakehouse on top of object storage to power your AI workflows.
  license: Apache-2.0
  license_file:
    - LICENSE
    - python/LICENSE
    - THIRDPARTY.yml
  license_family: Apache
  dev_url: https://github.com/lance-format/lance
  doc_url: https://lance.org/

extra:
  recipe-maintainers:
    - yhori991
